site_name: HyperDex Software Stack
theme:
  name: material
  logo: images/logo_white.png
  favicon: images/favicon.png
  palette:
    primary: black
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.select
  font:
    text: Roboto

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition

nav:
  - Getting Started:
      - HyperDex Installation: install_hyperdex.md
      - Quick Start: quick_start.md
    #      - Overview: install_guide.md
    #      - Install XRT: I_xrt.md
    #      - Install HRT: I_hrt.md
    #      - Install Compiler: I_compiler.md
    #  - Quick Start with Python: quick_start.md
  - HyperDex Software:
      - SDK:
          - Hyperdex Toolchain: hyperdex_toolchain.md
          - Supported Models: supported_models.md
      - Inference:
          - Offline Infereence: Offline_Inference.md
          - Online Inference: Online_Inference.md
      # - API:
      #     - Python API: python_api.md
      #     - vLLM API: vllm_api.md
      # - Serving:
      #     - TGI Server: tgi_serve.md
      #     - vLLM Server: vllm_serve.md
      # - SDK:
      #     - Model Compilation: model_compile.md
      #     - Supported Models: supported_models.md
      - Chat UI: chat_ui.md
          # - Chat-UI with LPU: chat_ui.md
        #  - Deploying with Docker(WIP): docker.md
  # - About LPU:
      # - Useful Commands: trouble_shoot.md
    #  - Performance: performance.md
  - Q&A:
      - Useful Commands: trouble_shoot.md
      - About Server: QA_server.md
      - About Device: QA_device.md
      - About Software: QA_software.md
# Want to add: sw_overview, performance, docker
# Unsed: install_guide, install_xrt, install_hrt
copyright: Copyright &copy; 2023 - 2024 HyperAccel Inc.
extra:
  generator: false
