site_name: HyperDex Software Stack
theme:
  name: material
  logo: images/logo_white.png
  favicon: images/favicon.png
  palette:
    primary: black
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.select
  font:
    text: Roboto

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition

nav:
  - Getting Started:
      - HyperDex Installation: install_hyperdex.md
      - Quick Start: quick_start.md
  - HyperDex Software:
      - SDK:
          - Hyperdex Toolchain: hyperdex_toolchain.md
          - Supported Models: supported_models.md
      - Inference:
          - Offline Inference: 
              - HuggingFace API: huggingface_api.md
              - vLLM API: offline_inference.md
          - Online Inference: 
              - vLLM server: online_inference.md
              - OpenAI compatible server: online_inference_openai.md
      - Chat UI: chat_ui.md
  - Q&A:
      - Useful Commands: useful_commands.md
      - About Server: about_server.md
      - About Device: about_device.md
      - About Software: about_software.md
# Want to add: sw_overview, performance, docker
# Unsed: install_guide, install_xrt, install_hrt
copyright: Copyright &copy; 2023 - 2024 HyperAccel Inc.
extra:
  generator: false
